In [1]:
print("Hello world")

Hello world


In [2]:
nums = [0, 1, 2, 3, 4]
squares = [x ** 2 for x in nums]
print (squares)

[0, 1, 4, 9, 16]


In [3]:
import numpy as np
a = np.zeros((2,2))  # Create an array of all zeros
print (a)
c = np.full((2,2), 7) # Create a constant array
print (c) 

d = np.eye(2)        # Create a 2x2 identity matrix
print (d)

[[0. 0.]
 [0. 0.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
